apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: customercli
  name: customercli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customercli
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: customercli
    spec:
      containers:
      - command:
        - CompileDaemon
        - --build=go build -o customerClient ./customer/client/
        - --command=./customerClient
        env:
        - name: MICRO_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: MICRO_SERVER_ADDRESS
              name: customer-docker-compose-cli-env
        image: customercli
        imagePullPolicy: ""
        name: customerclicont
        ports:
        - containerPort: 50051
        resources: {}
#        volumeMounts:
#        - mountPath: /go/src/goTemp/customer/client
#          name: customercli-claim0
      restartPolicy: Always
      serviceAccountName: ""
#      volumes:
#      - name: customercli-claim0
#        persistentVolumeClaim:
#          claimName: customercli-claim0
