apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: usercli
  name: usercli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usercli
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: usercli
    spec:
      containers:
      - command:
        - CompileDaemon
        - --build=go build -o userClient ./user/client/
        - --command=./userClient
        env:
        - name: MICRO_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: MICRO_SERVER_ADDRESS
              name: user-docker-compose-cli-env
        image: usercli
        imagePullPolicy: ""
        name: userclicont
        ports:
        - containerPort: 50051
        resources: {}
#        volumeMounts:
#        - mountPath: /go/src/goTemp/user/client
#          name: usercli-claim0
      restartPolicy: Always
      serviceAccountName: ""
#      volumes:
#      - name: usercli-claim0
#        persistentVolumeClaim:
#          claimName: usercli-claim0
