// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: globalProtos/standardFields.proto

package globalProtos

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GlModification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateDate *timestamp.Timestamp `protobuf:"bytes,1,opt,name=createDate,proto3" json:"createDate,omitempty"`
	UpdateDate *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updateDate,proto3" json:"updateDate,omitempty"`
	ModifiedBy string               `protobuf:"bytes,3,opt,name=modifiedBy,proto3" json:"modifiedBy,omitempty"`
}

func (x *GlModification) Reset() {
	*x = GlModification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_globalProtos_standardFields_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlModification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlModification) ProtoMessage() {}

func (x *GlModification) ProtoReflect() protoreflect.Message {
	mi := &file_globalProtos_standardFields_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlModification.ProtoReflect.Descriptor instead.
func (*GlModification) Descriptor() ([]byte, []int) {
	return file_globalProtos_standardFields_proto_rawDescGZIP(), []int{0}
}

func (x *GlModification) GetCreateDate() *timestamp.Timestamp {
	if x != nil {
		return x.CreateDate
	}
	return nil
}

func (x *GlModification) GetUpdateDate() *timestamp.Timestamp {
	if x != nil {
		return x.UpdateDate
	}
	return nil
}

func (x *GlModification) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

type GlValidityDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidFrom *timestamp.Timestamp `protobuf:"bytes,1,opt,name=validFrom,proto3" json:"validFrom,omitempty"`
	ValidThru *timestamp.Timestamp `protobuf:"bytes,2,opt,name=validThru,proto3" json:"validThru,omitempty"`
}

func (x *GlValidityDate) Reset() {
	*x = GlValidityDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_globalProtos_standardFields_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlValidityDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlValidityDate) ProtoMessage() {}

func (x *GlValidityDate) ProtoReflect() protoreflect.Message {
	mi := &file_globalProtos_standardFields_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlValidityDate.ProtoReflect.Descriptor instead.
func (*GlValidityDate) Descriptor() ([]byte, []int) {
	return file_globalProtos_standardFields_proto_rawDescGZIP(), []int{1}
}

func (x *GlValidityDate) GetValidFrom() *timestamp.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *GlValidityDate) GetValidThru() *timestamp.Timestamp {
	if x != nil {
		return x.ValidThru
	}
	return nil
}

var File_globalProtos_standardFields_proto protoreflect.FileDescriptor

var file_globalProtos_standardFields_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73,
	0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x0e, 0x47, 0x6c, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x79, 0x22,
	0x84, 0x01, 0x0a, 0x0e, 0x47, 0x6c, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x38, 0x0a, 0x09,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x68, 0x72, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x54, 0x68, 0x72, 0x75, 0x42, 0x15, 0x5a, 0x13, 0x67, 0x6f, 0x54, 0x65, 0x6d, 0x70,
	0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_globalProtos_standardFields_proto_rawDescOnce sync.Once
	file_globalProtos_standardFields_proto_rawDescData = file_globalProtos_standardFields_proto_rawDesc
)

func file_globalProtos_standardFields_proto_rawDescGZIP() []byte {
	file_globalProtos_standardFields_proto_rawDescOnce.Do(func() {
		file_globalProtos_standardFields_proto_rawDescData = protoimpl.X.CompressGZIP(file_globalProtos_standardFields_proto_rawDescData)
	})
	return file_globalProtos_standardFields_proto_rawDescData
}

var file_globalProtos_standardFields_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_globalProtos_standardFields_proto_goTypes = []interface{}{
	(*GlModification)(nil),      // 0: GlModification
	(*GlValidityDate)(nil),      // 1: GlValidityDate
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_globalProtos_standardFields_proto_depIdxs = []int32{
	2, // 0: GlModification.createDate:type_name -> google.protobuf.Timestamp
	2, // 1: GlModification.updateDate:type_name -> google.protobuf.Timestamp
	2, // 2: GlValidityDate.validFrom:type_name -> google.protobuf.Timestamp
	2, // 3: GlValidityDate.validThru:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_globalProtos_standardFields_proto_init() }
func file_globalProtos_standardFields_proto_init() {
	if File_globalProtos_standardFields_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_globalProtos_standardFields_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlModification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_globalProtos_standardFields_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlValidityDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_globalProtos_standardFields_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_globalProtos_standardFields_proto_goTypes,
		DependencyIndexes: file_globalProtos_standardFields_proto_depIdxs,
		MessageInfos:      file_globalProtos_standardFields_proto_msgTypes,
	}.Build()
	File_globalProtos_standardFields_proto = out.File
	file_globalProtos_standardFields_proto_rawDesc = nil
	file_globalProtos_standardFields_proto_goTypes = nil
	file_globalProtos_standardFields_proto_depIdxs = nil
}
