{
 "title": "goTemp Services",
 "description": "goTemp services dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "gotempname", "label": "Service", "query": { "query": "label_values(goTemp_name)" } },
   { "name": "gotempendpoint", "label": "Endpoint", "query": { "query": "label_values(goTemp_endpoint)" } }
  ]
 },
 "panels": [
  {
   "title": "Total endpoint hits",
   "type": "stat",
   "description": "Total endpoint hits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(goTemp_request_total)" }
   ]
  },
  {
   "title": "Endpoint hit count by Service",
   "type": "stat",
   "description": "Endpoint hit count by Service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (goTemp_name)(goTemp_request_total)",
     "legendFormat": "{{goTemp_endpoint}}"
    }
   ]
  },
  { "title": "Metrics for selected service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request duration by end point for selected service",
   "type": "bargauge",
   "description": "Request duration by end point",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "goTemp_request_duration_seconds_bucket{goTemp_name=~\"$gotempname\",  goTemp_endpoint=~\"$gotempendpoint\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Endpoint hit count for selected service",
   "type": "piechart",
   "description": "Endpoint hit count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "goTemp_latency_microseconds_count{goTemp_name=~\"$gotempname\"}"
    }
   ]
  }
 ]
}